options:
  merge-default-rules: false
rules:
  extends-before-declarations: 2
  mixins-before-declarations: 2
  one-declaration-per-line: 2
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties:
    - 2
    - exclude: [background]
  no-empty-rulesets: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 2
  pseudo-element: 2
  quotes:
    - 2
    - style: single
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-brace: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format: 2
  attribute-quotes: 2
  border-zero: 2
  brace-style: 2
  class-name-format: 0
  declarations-before-nesting: 2
  empty-args: 2
  final-newline: 2
  indentation: 2
  leading-zero:
    - 2
    - include: true
  max-line-length:
    - 2
    - length: 140
  mixin-name-format: 2
  